src/msim/_/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    path("accounts/", include("registration.urls")),
    path("mortgages/", include("mortgages.urls")),

    path("", include("website.urls")),
]

src/msim/mortgages/urls.py
from django.urls import path

from .views import (
    ActualInitialPaymentSet,
    ActualThereafterPaymentSet,
    DiscrepancyDelete,
    DiscrepancyCreateUpdate,
    MortgageCreate,
    MortgageDelete,
    MortgageDetail,
    MortgageDuplicate,
    MortgageList,
    MortgageUpdate,
    OverpaymentDelete,
    OverpaymentCreateUpdate,
    Speculate,
)


app_name = "mortgages"
urlpatterns = [
    path("", MortgageList.as_view(), name="list"),
    path("create/", MortgageCreate.as_view(), name="create"),
    path("<int:pk>/update/", MortgageUpdate.as_view(), name="update"),
    path("<int:pk>/", MortgageDetail.as_view(), name="detail"),
    path(
        "<int:pk>/set_initial/",
        ActualInitialPaymentSet.as_view(),
        name="actualinitialpayment.set",
    ),
    path(
        "<int:pk>/set_thereafter/",
        ActualThereafterPaymentSet.as_view(),
        name="actualthereafterpayment.set",
    ),
    path("<int:pk>/duplicate/", MortgageDuplicate.as_view(), name="duplicate"),
    path("<int:pk>/delete/", MortgageDelete.as_view(), name="delete"),
    path(
        "<int:pk>/overpayments/",
        OverpaymentCreateUpdate.as_view(),
        name="overpayment.create_update",
    ),
    path(
        "overpayments/<int:pk>/delete/",
        OverpaymentDelete.as_view(),
        name="overpayment.delete",
    ),
    path(
        "<int:pk>/discrepancies/",
        DiscrepancyCreateUpdate.as_view(),
        name="discrepancy.create_update",
    ),
    path(
        "discrepancies/<int:pk>/delete/",
        DiscrepancyDelete.as_view(),
        name="discrepancy.delete",
    ),
    path("<int:pk>/speculate/", Speculate.as_view(), name="speculate")
]

src/msim/website/urls.py
from django.urls import path

from .views import Home


urlpatterns = [
    path("", Home.as_view()),
]

src/msim/website/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "home.html"

src/msim/website/templates/_user_menu.html
<p>
  {% if user.is_authenticated %}
    {{ user.username }} -
    <a href="{% url 'logout' %}">Logout</a>
  {% else %}
    <a href="{% url 'register' %}">Register</a>
  {% endif %}
</p>

src/msim/website/templates/base.html
<!doctype html>

<html>
<head>
  <style>{% include "base.css" %}</style>
  <title>msim</title>
</head>
<body>
  {% include "_user_menu.html" %}
  {% block content %}{% endblock %}

  {% block js %}
    <script>
      {% include "base.js" %}
    </script>
  {% endblock %}
</body>
</html>

src/msim/website/templates/home.html
{% extends "base.html" %}

{% block content %}
  <a href="{% url 'mortgages:list' %}">Mortgages</a>
{% endblock %}