src/msim/_/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    path("accounts/", include("registration.urls")),
    path("mortgages/", include("mortgages.urls")),

    path("", include("website.urls")),
]

src/msim/mortgages/urls.py
from django.urls import path

from .views import (
    ActualInitialPaymentSet,
    ActualThereafterPaymentSet,
    DiscrepancyDelete,
    DiscrepancyCreateUpdate,
    MortgageCreate,
    MortgageDelete,
    MortgageDetail,
    MortgageDuplicate,
    MortgageList,
    MortgageUpdate,
    OverpaymentDelete,
    OverpaymentCreateUpdate,
    Speculate,
)


app_name = "mortgages"
urlpatterns = [
    path("", MortgageList.as_view(), name="list"),
    path("create/", MortgageCreate.as_view(), name="create"),
    path("<int:pk>/update/", MortgageUpdate.as_view(), name="update"),
    path("<int:pk>/", MortgageDetail.as_view(), name="detail"),
    path(
        "<int:pk>/set_initial/",
        ActualInitialPaymentSet.as_view(),
        name="actualinitialpayment.set",
    ),
    path(
        "<int:pk>/set_thereafter/",
        ActualThereafterPaymentSet.as_view(),
        name="actualthereafterpayment.set",
    ),
    path("<int:pk>/duplicate/", MortgageDuplicate.as_view(), name="duplicate"),
    path("<int:pk>/delete/", MortgageDelete.as_view(), name="delete"),
    path(
        "<int:pk>/overpayments/",
        OverpaymentCreateUpdate.as_view(),
        name="overpayment.create_update",
    ),
    path(
        "overpayments/<int:pk>/delete/",
        OverpaymentDelete.as_view(),
        name="overpayment.delete",
    ),
    path(
        "<int:pk>/discrepancies/",
        DiscrepancyCreateUpdate.as_view(),
        name="discrepancy.create_update",
    ),
    path(
        "discrepancies/<int:pk>/delete/",
        DiscrepancyDelete.as_view(),
        name="discrepancy.delete",
    ),
    path("<int:pk>/speculate/", Speculate.as_view(), name="speculate")
]

src/msim/mortgages/forms.py
from django import forms

from .models import Mortgage


class ActualPaymentSet(forms.Form):
    actual_payment = forms.DecimalField()

    def __init__(self, *args, model, mortgage, **kwargs):
        super().__init__(*args, **kwargs)

        self.model = model
        self.mortgage = mortgage

    def save(self):
        default = self.model.get_default(self.mortgage)
        if self.cleaned_data["actual_payment"] == default:
            self.model.objects.for_mortgage(self.mortgage).delete()

            return

        self.model.objects.update_or_create(
            mortgage=self.mortgage,
            defaults={"amount": self.cleaned_data["actual_payment"]},
        )


class AmountCreateUpdate(forms.Form):
    amount = forms.DecimalField()
    month = forms.IntegerField()
    mortgage = forms.ModelChoiceField(queryset=Mortgage.objects.all())

    def __init__(self, *args, model, **kwargs):
        super().__init__(*args, **kwargs)

        self.model = model

    def save(self):
        self.model.objects.update_or_create(
            mortgage=self.cleaned_data["mortgage"],
            month=self.cleaned_data["month"],
            defaults={"amount": self.cleaned_data["amount"]},
        )


class MortgageDuplicate(forms.Form):

    def __init__(self, *args, mortgage, **kwargs):
        super().__init__(*args, **kwargs)

        self.mortgage = mortgage

    def save(self):
        return self.mortgage.duplicate()


class SpeculateForm(forms.Form):
    amount = forms.DecimalField()
    month = forms.TypedChoiceField(coerce=int)

    def __init__(self, *args, month_choices, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["month"].choices = month_choices

src/msim/mortgages/views.py
from copy import deepcopy
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    ListView,
    UpdateView,
)
from django.views.generic.detail import SingleObjectMixin

from . import forms
from .models import (
    ActualInitialPayment,
    ActualThereafterPayment,
    Discrepancy,
    Ledger,
    Mortgage,
    Overpayment,
)


class MortgageCreateUpdateMixin:
    model = Mortgage
    fields = [
        "start_date",
        "amount",
        "term",
        "initial_period",
        "interest_rate_initial",
        "interest_rate_thereafter",
        "income",
        "expenditure",
        "default_overpayment_initial",
        "default_overpayment_thereafter",
    ]


class MortgageCreate(
    LoginRequiredMixin,
    MortgageCreateUpdateMixin,
    CreateView,
):

    def form_valid(self, form):
        form.instance.owner = self.request.user

        return super().form_valid(form)


class OwnerMixin:

    def get_queryset(self):
        return super().get_queryset().owned_by(self.request.user)


class MortgageUpdate(
    LoginRequiredMixin,
    MortgageCreateUpdateMixin,
    OwnerMixin,
    UpdateView,
):
    pass


class MortgageList(LoginRequiredMixin, OwnerMixin, ListView):
    model = Mortgage


class MortgageDetail(LoginRequiredMixin, OwnerMixin, DetailView):
    model = Mortgage

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ledger = Ledger(mortgage=self.object)
        cost = ledger.calculate_cost()

        without_overriden_overpayments = {}
        for month in ledger.overpayments:
            without_overridden_overpayment = deepcopy(ledger)
            without_overridden_overpayment.delete_overpayment(month)
            cost_without_overpayment = (
                without_overridden_overpayment.calculate_cost()
            )

            # Positive for greater total cost.
            without_overriden_overpayments[month] = (
                cost_without_overpayment - cost
            )

        return {
            **context,
            "ledger": ledger.ledger,
            "total_cost": cost,
            "average_overpayment": (
                self.object.overpayments
                .in_the_past()
                .average()
            ),
            "what_could_have_been": without_overriden_overpayments,
            "speculate_form": forms.SpeculateForm(
                month_choices=ledger.month_choices,
            )
        }


class ActualPaymentSet(
    LoginRequiredMixin,
    OwnerMixin,
    SingleObjectMixin,
    FormView,
):
    model = Mortgage
    form_class = forms.ActualPaymentSet
    template_name = "mortgages/actualpayment_set.html"
    actual_payment_model = None

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        self.object = self.get_object()

    def get_form_kwargs(self):
        if self.actual_payment_model is None:
            raise ImproperlyConfigured("no")

        return {
            **super().get_form_kwargs(),
            "model": self.actual_payment_model,
            "mortgage": self.object,
        }

    def form_valid(self, form):
        form.save()

        return HttpResponseRedirect(self.object.get_absolute_url())


class ActualInitialPaymentSet(ActualPaymentSet):
    actual_payment_model = ActualInitialPayment


class ActualThereafterPaymentSet(ActualPaymentSet):
    actual_payment_model = ActualThereafterPayment


class MortgageDuplicate(
    LoginRequiredMixin,
    OwnerMixin,
    SingleObjectMixin,
    FormView,
):
    model = Mortgage
    form_class = forms.MortgageDuplicate
    template_name = "mortgages/mortgage_duplicate.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        self.object = self.get_object()

    def get_form_kwargs(self):
        return {
            **super().get_form_kwargs(),
            "mortgage": self.object,
        }

    def form_valid(self, form):
        mortgage = form.save()

        return HttpResponseRedirect(mortgage.get_absolute_url())


class MortgageDelete(LoginRequiredMixin, OwnerMixin, DeleteView):
    model = Mortgage
    success_url = reverse_lazy("mortgages:list")


class AmountOwnerMixin:

    def get_queryset(self):
        return super().get_queryset().owned_by(self.request.user)


class BaseAmountCreateUpdate(LoginRequiredMixin, AmountOwnerMixin, FormView):
    form_class = forms.AmountCreateUpdate

    def form_valid(self, form):
        form.save()

        return HttpResponse(status=204)

    def form_invalid(self, form):
        return HttpResponse(
            json.dumps(form.errors).encode("utf-8"),
            status=400,
            content_type="application/json",
        )

    def get_form_kwargs(self):
        kwargs = {
            **super().get_form_kwargs(),
            "model": self.model,
        }

        if "data" in kwargs:
            kwargs["data"] = kwargs["data"].copy()
            kwargs["data"]["mortgage"] = self.kwargs.get("pk")

        return kwargs


class DiscrepancyDelete(LoginRequiredMixin, AmountOwnerMixin, DeleteView):
    model = Discrepancy
    success_url = reverse_lazy("mortgages:list")


class DiscrepancyCreateUpdate(BaseAmountCreateUpdate):
    model = Discrepancy
    success_url = reverse_lazy("mortgages:list")
    fields = ["amount"]


class OverpaymentDelete(LoginRequiredMixin, AmountOwnerMixin, DeleteView):
    model = Overpayment
    success_url = reverse_lazy("mortgages:list")


class OverpaymentCreateUpdate(BaseAmountCreateUpdate):
    model = Overpayment
    success_url = reverse_lazy("mortgages:list")


class Speculate(LoginRequiredMixin, OwnerMixin, DetailView):
    model = Mortgage
    template_name_suffix = "_speculate"

    def get_context_data(self, **kwargs):
        ledger = Ledger(self.object)
        month_choices = ledger.month_choices
        form = forms.SpeculateForm(
            self.request.GET,
            month_choices=month_choices,
        )
        valid = form.is_valid()

        delta = None
        data = None
        no_money = False
        if valid:
            base_cost = ledger.calculate_cost()

            data = form.cleaned_data
            remaining = data['amount']
            month = data['month']
            while remaining > 0:
                overpayment = ledger.ledger[month].overpayment
                ledger.set_overpayment(
                    month,
                    Overpayment(amount=max(overpayment - remaining, 0)),
                )
                remaining -= overpayment
                month -= 1

                if month < 0:
                    no_money = True

                    break

            new_cost = ledger.calculate_cost()

            delta = base_cost - new_cost + data['amount']

        return {
            **super().get_context_data(**kwargs),
            "valid": valid,
            "form": form,
            "delta": delta,
            "data": data,
            "no_money": no_money,
            "month_names": dict(month_choices),
        }

src/msim/mortgages/templates/mortgages/_extra_cost.html
{% load abs %}
{% load add %}

Overpaying {{ entry.overpayment_delta|abs }}
{% with entry.overpayment_delta_positive as less %}
  {% if less %}
    less than usual <span class="costs">costs</span>
  {% else %}
    more than usual <span class="saves">saves</span>
  {% endif %}
{% endwith %}
you {{ extra_cost|abs }}
(making that delta worth {{ entry.overpayment_delta|add:extra_cost|abs }})

src/msim/mortgages/templates/mortgages/_ledgerentry_tds.html
{% load humanize %}

<td>{{ month_name }}</td>
<td>{{ opening_balance|intcomma }}</td>
<td>{{ interest|intcomma }}</td>
<td>{{ payment|intcomma }}</td>
<td>
  {% include "mortgages/_ledgerentryamount.html" with amount=overpayment %}
</td>
<td>
  {% include "mortgages/_ledgerentryamount.html" with amount=discrepancy %}
</td>
<td>{{ closing_balance|intcomma }}</td>

src/msim/mortgages/templates/mortgages/_ledgerentryamount.html
{% load humanize %}

<input
  name="{{ amount.name }}"
  id="{{ amount.name }}"
  value="{{ amount.amount }}"
/>

<button
  data-name="{{ amount.name }}"
  data-url="{% url amount.create_update pk=amount.ledger_entry.mortgage_pk %}"
  onclick="amountSave(
    this.dataset.url,
    this.dataset.name,
    {{ amount.month_number}}
  )"
  type="button"
>
  SAVE
</button>

{% if amount.pk %}
  <button
    data-url="{% url amount.delete pk=amount.pk %}"
    onclick="amountDelete(this.dataset.url)"
    type="button"
  >
    DELETE
  </a>
{% endif %}

src/msim/mortgages/templates/mortgages/actualpayment_set.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Set</button>
  </form>
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <p>For sure delete, my dude?</p>
    <button type="submit">Delete</button>
  </form>
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_detail.html
{% extends "base.html" %}

{% load get %}
{% load humanize %}

{% block content %}
  <h1>{{ mortgage }}</h1>

  <p><a href="{% url 'mortgages:list' %}">&lt; Mortgages</a></p>

  <ul>
    <li>
      <a href="{% url 'mortgages:update' pk=mortgage.pk %}">
        Edit this mortgage
      </a>
    </li>
    <li>
      Set actual payment for
      <a href="{% url 'mortgages:actualinitialpayment.set' pk=mortgage.pk %}">
        intial period
      </a>
      /
      <a
        href="{% url 'mortgages:actualthereafterpayment.set' pk=mortgage.pk %}"
      >
        thereafter
      </a>
    </li>
    <li>
      <a href="{% url 'mortgages:delete' pk=mortgage.pk %}">
        Delete this mortgage
      </a>
    </li>
    <li>
      <form
        action="{% url 'mortgages:duplicate' pk=mortgage.pk %}"
        method="POST"
      >
        {% csrf_token %}
        <button type="submit">Duplicate this mortgage</button>
      </form>
    </li>
  </ul>

  <h2>Summary</h2>

  <table>
    <thead>
      <th>End date</th>
      <th>Total cost</th>
      <th>Average overpayment so far</th>
    </thead>
    <tr>
      <td>
        {% with ledger|last as entry %}
          {{ entry.year }}-{{ entry.month|stringformat:"02d" }}
        {% endwith %}
      </td>
      <td>{{ total_cost|intcomma }}</td>
      <td>{{ average_overpayment|floatformat:2 }}</td>
    </tr>
  </table>

  <hr />

  <h2>Speculation</h2>

  <form
    action="{% url 'mortgages:speculate' pk=mortgage.pk %}"
    method="GET"
    id="speculateForm"
  >
    <span>
      How much will spending a certain amount on a certain month cost
      in the long run?
    </span>
    {{ speculate_form.as_p }}
    <a href="#" onclick="speculateForm.submit()">Speculate</a>
  </form>

  <hr />

  <h2>Details</h2>

  <table>
    <thead>
      <th>Date</th>
      <th>Opening balance</th>
      <th>Interest</th>
      <th>Payment</th>
      <th>Overpayment</th>
      <th>Discrepancy</th>
      <th>Closing balance</th>
    </thead>
    {% for entry in ledger %}
      <tr>
        {{ entry.as_tds }}
        <td>
          {% with what_could_have_been|get:forloop.counter0 as extra_cost %}
            {% if extra_cost is not None %}
              {% include "mortgages/_extra_cost.html" %}
            {% endif %}
          {% endwith %}
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

{% block js %}
  {{ block.super }}
  <script>
    {% include "mortgages/base.js" %}
  </script>
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_duplicate.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Duplicate</button>
  </form>
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_form.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if mortgage %}Edit{% else %}Create{% endif %}
    </button>
  </form>
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Mortgages</h1>

  <p>
    <a href="{% url 'mortgages:create' %}">Create new</a>
  {% for mortgage in mortgage_list %}
    <form
      action="{% url 'mortgages:duplicate' pk=mortgage.pk %}"
      method="POST"
    >
      <p>
        <a href="{{ mortgage.get_absolute_url }}">{{ mortgage }}</a>
        -
        <a href="{% url 'mortgages:delete' pk=mortgage.pk %}">Delete</a>
          {% csrf_token %}
          <button type="submit">Duplicate</button>
      </p>
    </form>
  {% empty %}
    <p>nothin'</p>
  {% endfor %}
{% endblock %}

src/msim/mortgages/templates/mortgages/mortgage_speculate.html
{% extends "base.html" %}

{% load get %}
{% load humanize %}

{% block content %}
  <h1>Speculated spending</h1>

  <p>
    <a href="{% url 'mortgages:list' %}">&lt; Mortgages</a>
    /
    <a href="{% url 'mortgages:detail' pk=mortgage.pk %}">{{ mortgage }}</a>
  </p>

  <form action="" method="GET" id="speculateForm">
    {{ form.as_p }}
    <a href="#" onclick="speculateForm.submit()">Speculate again!</a>
  </form>

  <p>
    {% if valid %}
      {% if no_money %}
        You do not have enough time to save up
        {{ data.amount|intcomma }} by month {{ data.month }} by cutting
        overpayments.
      {% else %}
        Cutting overpayments to spend {{ data.amount|intcomma }} in
        {{ month_names|get:data.month }} will cost you
        {{ delta|intcomma }} over the period of the mortgage.  Are you
        sure you wanna do that?
      {% endif %}
    {% else %}
      {# Super user unfriendly - whatever. #}
      Malformed speculation data, go back and try again.

      {{ form.errors }}
    {% endif %}
{% endblock %}